### BASICS OF DATA SCIENCE NUMPY LIBRARY

What is numpy?
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

What is an array?
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
# import the numpy library 
import numpy as np

In [2]:
#create an array by areating a list and then coverting that lsit to an array.
list =[1,2,3,4] # crated a list
array = np.array(list) # converting list to array with np.array function

In [3]:
print(array) # to check our numpy array

[1 2 3 4]


In [4]:
type(array) # to check the data type

numpy.ndarray

In [5]:
array.shape # shows one dimensional array

(4,)

In [6]:
# Create a multinested array
list1= [1,2,3,4]
list2=[5,6,7,8]
list3=[9,0,2,3]

array2= np.array([list1, list2, list3])

In [7]:
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 2, 3]])

In [8]:
array2.shape # the array shows that we have 3 rows and four columns

(3, 4)

In [9]:
# we can change the shape of the array by using .reshape() function
array2.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 2, 3]])

### Indexing

In [10]:
array=np.array(list2)
array

array([5, 6, 7, 8])

In [11]:
array[2]  # for indexing we always use the sqaure brackets and indexing starts from 0 .
          # so, the index od 5 is 0 ,6 is 1 ,7 is 2 and 8 is 3.

7

In [12]:
# indexing in 2 dimensional array
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 2, 3]])

In [13]:
array2[:,:] # left hand side of the comma represents the row selection and right hand side 
          #column selection, [:,:] shows that we are choosing the entire row and entire column

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 2, 3]])

In [14]:
array2[0:2,0:3] # so, if we want to select the first two rows and the first thre e columns.

array([[1, 2, 3],
       [5, 6, 7]])

In [15]:
array2[1:,2:] # the indexing of row and column also starts from 0

array([[7, 8],
       [2, 3]])

In [16]:
 # we use ,arrange() function to arrange the array. 
array

array([5, 6, 7, 8])

In [17]:
array= np.arange(0,6) # the array has been arranged from 0 t 5.
array

array([0, 1, 2, 3, 4, 5])

In [18]:
### Copy and broadcasting
array

array([0, 1, 2, 3, 4, 5])

In [19]:
array[3:]=100

In [20]:
array # the value after the 3 index changed to 100

array([  0,   1,   2, 100, 100, 100])

In [21]:
array1= array

In [22]:
array1[3:]=500
array1

array([  0,   1,   2, 500, 500, 500])

In [23]:
array # same changes happened in both the array because hay share the same memory point.
      # any change in one will reflect in other.

array([  0,   1,   2, 500, 500, 500])

In [24]:
# so, in order to prevent this we use .copy()
array1=array.copy()

In [25]:
array1[3:]=200
array1

array([  0,   1,   2, 200, 200, 200])

In [26]:
array

array([  0,   1,   2, 500, 500, 500])

### some useful conditions of numpy for exploratory data analysis

In [27]:
val =2 
array<2 # we get true and false for all the emelents in array.

array([ True,  True, False, False, False, False])

In [28]:
val =2
array*2 # all the elements get multiplied by 2 

array([   0,    2,    4, 1000, 1000, 1000])

In [29]:
val =3
array/3

array([  0.        ,   0.33333333,   0.66666667, 166.66666667,
       166.66666667, 166.66666667])

In [30]:
np.arange(0,10).reshape(5,2) # creates an array of 0 to 10 with 5 rows and 2 col.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
array4=np.arange(1,11).reshape(2,5) # since there are 10 numbers we will have to create an aarray of 2,5 dimension 
#so, that i can contain the exact 10 values

In [32]:
array5=np.arange(2,12).reshape(2,5)

In [33]:
array4*array5

array([[  2,   6,  12,  20,  30],
       [ 42,  56,  72,  90, 110]])

In [34]:
# we can create an array of 1 with np.ones
np.ones(5, dtype= int)

array([1, 1, 1, 1, 1])

In [35]:
np.ones((2,6),dtype=float) # created 2 dimensional array with float dtype

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
# random distribution
np.random.rand(3,3)  #Create an array of the given shape and populate it with random samples from a uniform distribution

array([[0.57807465, 0.1966048 , 0.08295592],
       [0.49833323, 0.89571558, 0.96499674],
       [0.42623014, 0.31828668, 0.82371907]])

In [37]:
array6=np.random.randn(4,4) 

In [38]:
array6

array([[-0.99656731, -1.12468105,  1.15676673,  0.2852193 ],
       [ 0.0202129 ,  0.27816863, -0.84859262, -0.73161507],
       [-0.23768898, -0.70805441, -0.3713835 ,  0.16103572],
       [-2.46775637,  0.99012194, -0.5975627 , -0.68269631]])